### ISSUE TITLE
Possible to Append an existing invoice with additional Line Items

### ISSUE THREAD

**Issue by madteckhead** [freakboy3742/pyxero#63] opened 2015-02-15 02:12 UTC
I could not find any reference as to how one would edit an existing invoice and / or add line items to it. Our use case is that we have some repeating invoices, and we want to add some variable costs from timesheets onto them before sending them out. 

My test: 
```
ipdb> items = invoice['LineItems']
ipdb> invoice['LineItems'] = items + items
ipdb> xero.invoices.save(invoice)
*** XeroBadRequest: Object reference not set to an instance of an object.
```

**Comment by madteckhead** [comment] 2015-02-15 02:26
A simpler example:
"""
ipdb>  invoice = xero.invoices.get('INV-9012')
ipdb> xero.invoices.save(invoice)
*** XeroBadRequest: Object reference not set to an instance of an object.
"""

**Comment by madteckhead** [comment] 2015-02-15 02:59
Okay I've narrowed it down. The problem is caused by trying to update with two tracking codes being used. I've one defined as 'HH - Jobs' and another as 'HH - Services'. I'm able to save wither one, or no tracking codes but not both at once. 

Was just testing with a command like this and changing line item options to see which one was making it bork. 

```
ipdb> xero.invoices.save(xero.invoices.get('INV-9014'))
```

Since our repeating invoice already uses both tracking codes, its impossible to update as a line item with two codes causes the `*** XeroBadRequest: Object reference not set to an instance of an object.` error.

**Comment by madteckhead** [comment] 2015-02-15 04:36
Pretty sure its related to TrackingCategoryID being returned, but not working in the put/save. I've had 'TrackingCategory' working... note they are encapsulated differently too... [,] vs (,)

The formats are quite different between the two... 

Sample Data: 

What is being returned by .get
```
[{u'AccountCode': u'200', u'TaxAmount': u'1.50', u'Tracking': [{u'TrackingCategoryID': u'xxxxxxxxx-3222-4cd6-8f31-2e01e696e2d8', u'Name': u'HH - Services', u'Option': u'Administration'}, {u'TrackingCategoryID': u'xxxxxxxxxxxx-4f36-a511-0d45f22c107e', u'Name': u'HH - Jobs', u'Option': u'REDACTED'}], u'Description': u'QC-687 - Icon Generator crash: unsafe access from multi-process. - (Hourly)', u'UnitAmount': u'15.00', u'TaxType': u'OUTPUT', u'LineAmount': u'15.00', u'Quantity': u'1.0000'}]
```

Format I've previously been uploading that is working:
```
ipdb> items[0]
{'AccountCode': '200', 'Tracking': ({'TrackingCategory': {'Name': 'HH - Services', 'Option': 'Mobile apps'}}, {'TrackingCategory': {'Name': 'HH - Jobs', 'Option': 'Job Name Redacted'}}), 'Description': u'QC-687 - Icon Generator crash: unsafe access from multi-process. - (Hourly)', 'UnitAmount': '15.00', 'TaxType': 'OUTPUT', 'Quantity': '1.0'}
```

Gotta jump on a plane, but totally a small $30 bounty for fixing this ASAP. 

Thanks.

**Comment by MJMortimer** [comment] 2015-02-19 23:37
I've been taking a look into this and it has something to do with how the dictionary is created from the DOM object. It seems that when the 'Tracking' object is created, if it has more than one TrackingCategory object it won't actually create a TrackingCategory object for each. The same thing happens if there is more than one Lineitem, and you will most likely see the same thing in the Contact object for addresses and phones

**Comment by MJMortimer** [comment] 2015-02-20 01:13
TrackingCategories are a tricky one when there are more than applied. 

The problem is in this section of code when trying to convert the dict back into xml:

            elif is_list:
                # key name is a plural. This means each item
                # in the list needs to be wrapped in an XML
                # node that is a singular version of the list name.
                if is_plural:
                    for d in sub_data:
                        plural_name = self.PLURAL_EXCEPTIONS.get(plural_name, plural_name)
                        self.dict_to_xml(SubElement(elm, plural_name), d)

                # key name isn't a plural. Just insert the content
                # as an XML node with subnodes
                else:
                    for d in sub_data:
                        self.dict_to_xml(elm, d)

The Tracking is a list but it is not plural and so it just dumps the data for each TrackingCategory inside the Tracking without surrounding the data in TrackingCategory tags. A quick fix for this could be to change the above code to check for this situation and amend it like so:

             elif is_list:
                # key name is a plural. This means each item
                # in the list needs to be wrapped in an XML
                # node that is a singular version of the list name.
                if is_plural:
                    for d in sub_data:
                        plural_name = self.PLURAL_EXCEPTIONS.get(plural_name, plural_name)
                        self.dict_to_xml(SubElement(elm, plural_name), d)

                # key name isn't a plural. 
                # Is it the tricky Tracking list?
                elif key == 'Tracking':
                    for d in sub_data:
                        self.dict_to_xml(SubElement(elm, "TrackingCategory"), d)

                #Just insert the content
                # as an XML node with subnodes
                else:
                    for d in sub_data:
                        self.dict_to_xml(elm, d)

It isn't exactly elegant but it will fix your current situation

**Comment by madteckhead** [comment] 2015-02-20 01:23
This is the hacky work around that I came up with to get the job done without upstream changes!

```
invoice = xero.invoices.get(prompt)
            existingitems = []

            for item in invoice['LineItems']:
                tracking = item['Tracking']
                fixtracking = []
                for cat in tracking:
                    try:
                        cat.pop('TrackingCategoryID')
                    except:
                        pass
                    fixtracking.append({'TrackingCategory' : cat})

                item['Tracking'] = tuple(fixtracking)
                existingitems.append(item)

            invoice['LineItems'] = existingitems + items
```

**Comment by aidanlister** [comment] 2015-02-20 01:40
Could Tracking be added to the is_plural check?

**Comment by MJMortimer** [comment] 2015-02-20 01:56
I don't think so because if only one tracking category was used on a line item it doesnt create a list for tracking. 

If one tracking category is used:
  
    'Tracking': {'TrackingCategory': {'Name': 'ABC', 'TrackingCategoryID': '73ce1de8-0661-48c2-8c24-e70e2b261b7b', 'Option': 'B'}}

If two tracking categories are used:

    'Tracking': [{'TrackingCategoryID': '73ce1de8-0661-48c2-8c24-e70e2b261b7b', 'Name': 'ABC', 'Option': 'A'}, {'TrackingCategoryID': '01bb7aa9-d6d7-4963-a6e0-ba7f0d604c5e', 'Name': 'DEF', 'Option': 'D'}]}}

**Comment by MJMortimer** [comment] 2015-02-20 02:02
Scratch that. The check for if it's a list comes before the isPlural check so it could work. An exception would also need to be added to the PLURAL_EXCEPTIONS dictionary for 'trackin' : 'TrackingCategory'

**Comment by aidanlister** [comment] 2015-06-06 07:52
This should be fixed in the new version ...

**Closed by aidanlister** 2015-06-06 07:52 UTC
