### ISSUE TITLE
Binary file attachment issue

### ISSUE THREAD

**Issue by bpotard** [freakboy3742/pyxero#320] opened 2021-11-15 17:44 UTC
Hi there,

There appears to be a critical issue with uploading non ascii binary files as attachments in the current implementation, at least when using python 2.7.

It seems due to the fact that headers & auth tokens sent to the requests library in the wrapper should really **not** be unicode, ever. Arguably, this rarely causes any issue, as long as the payload is purely ASCII or unicode, which is (fortunately) most of the time in pyxero. However, it fails critically when uploading a binary file as an attachment (such as a png and most pdfs).

The error triggered is rather hard to comprehend, as it fails at a very low level:
```
>>> xero.invoices.put_attachment_data(<UUID>, "test.pdf", open("test.pdf", "rb").read(), "application/pdf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/xero/basemanager.py", line 240, in wrapper
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python2.7/httplib.py", line 1103, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1144, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1099, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 911, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 1: ordinal not in range(128)
```

Hacking httplib - which, to be fair, is trying to be too clever for its own good IMHO - fixes the issue, but this is not the point, as this is not something that should have to be done, and the error reflects that good practices have not been followed for the requests being sent - even though neither requests, requests-oauth, urllib or httplib itself ever complained about it. The issue here is that, because of the unicode headers, the internal "msg" buffer in httplib has been cast as an ascii encoded unicode object, so concatenating the binary payload triggers the exception, as it itself is then being interpreted as an ascii encoded unicode object.

For consistency with what the requests module returns (and what is expected in the multiple RFCs about http communications), my recommendation would be to convert the headers and auth - which will eventually be converted as an header - to "str". This way, even with binary payloads, there won't be any attempt at decoding.

As a workaround, I have written this small function:
```python
def asciify(d):
    import six
    from six import ensure_str as sstr
    ret = {}
    for k in d:
        if type(d[k]) == dict:
             ret[sstr(k)] = asciify(d[k])
        elif isinstance(d[k], six.string_types):
             ret[sstr(k)] = sstr(d[k])
        else:
             ret[sstr(k)] = d[k]
        return ret
```

... which I apply on the headers in the wrapper in the basemanager, as well as when initialising the credentials. This appears to fix the issue.

As my setup is rather unusual, it is not impossible that this is due to the some specific package versions - although I did try many different versions of requests / urllib3 / etc. Relevant packages installed:

```
Python 2.7.17
pyxero                        0.9.3
requests                      2.23.0
requests-oauthlib             1.3.0
urllib3                       1.25.8
```

**Comment by freakboy3742** [comment] 2021-11-15 22:59
The fact that this is hitting ascii codec encoding issues means it's almost 100% certain to be a problem with Python 2.7.  At this point, Python 2.7 has been fully EOL for almost 2 years, and all the packages you're depending on (including PyXero) have long since moved on. If you can reproduce this problem on Python 3, then I'm interested; but otherwise, I'm closing this as a "Won't fix" bug.

Some advice that you may want to pass to your Powers That Be: I can't speak for other projects; but from the perspective of PyXero, I'm not spending any of my volunteer time working on the support of a language that is 2 years past an extremely extended EOL. 

If your codebase is still on Python 2.7, you are building on a foundation of sand that is rapidly being eroded. There are very few projects in the Python ecosystem that will extend free support for users of Python 2.7 at this point, so if you want people to fix the bugs you find, you're probably going to need to start paying for that privilege. At some point, the cost of the consultants you're paying to keep your 2.7 codebase alive will exceed the cost of upgrading that codebase. 

If you can find a fix that doesn't impact Python 3 support, I'll consider it; but that patch will need to be accompanied with enough tests to verify that it won't break the Python 3 codebase, and will probably need to be accompanied by a monetary donation to make me care enough to take a look at the patch.

**Closed by freakboy3742** 2021-11-15 22:59 UTC

**Comment by bpotard** [comment] 2021-11-16 11:35
Hi there,

I can confirm the issue is affecting only python 2 code - I am trying to keep compatibility with python 2 in my code as it is needed in some configurations and I can confirm the exact same code runs fine in python 3.6. I would say that apart from calls handling binary data pyxero works also remarkably well with python2 (unlike other xero integrations that do not support it at all). And I apologise, I thought pyxero was still officially supporting python2.7 - as the latest packages are still distributed through PyPi - but that was my mistake!

In this particular case I would argue that the HTTP protocol has always only supported ASCII headers, so sending unicode headers is probably incorrect in the first place - but I you would also expect at least one of the underlying library to do the required conversion to the "right" data format if needed or complain rather than crash (which, in this case, should really be the lowest level library httplib from python2.7 which, after digging a bit, does the conversion for the values but not for the keys of the headers - go figure). So "won't fix" would probably be my answer as well 👍 

Best regards and keep up the good work,
Blaise

**Comment by bpotard** [comment] 2021-11-16 18:01
Hi again,

For what it's worth, I have now done a "fix" for the issue that does not involve changing the wrapper at all, and therefore should have a minimal impact overall. It is however rather ugly, and relies on the assumption that sending a file rather than a "str" will not lead to issues with decoding.

Here is the diff:
```
diff --git a/xero/basemanager.py b/xero/basemanager.py
index cbefe9e..f896f32 100644
--- a/xero/basemanager.py
+++ b/xero/basemanager.py
@@ -364,7 +364,7 @@ class BaseManager(object):
         uri = "/".join([self.base_url, self.name, id, "Attachments", filename])
         params = {"IncludeOnline": "true"} if include_online else {}
         headers = {"Content-Type": content_type, "Content-Length": str(len(data))}
-        return uri, params, "put", data, headers, False
+        return uri, params, "put", six.BytesIO(data), headers, False
 
     def put_attachment(self, id, filename, file, content_type, include_online=False):
         """Upload an attachment to the Xero object (from file object)."""
```

Not sure however if there are other places where unicode and binary data are mixed.
Let me know if that's an acceptable change, and I can send a PR.

Cheers,
Blaise
