### ISSUE TITLE
ImportError: No module named 'xero.auth'; 'xero' is not a package

### ISSUE THREAD

**Issue by johnnydisco** [freakboy3742/pyxero#198] opened 2017-08-20 08:37 UTC
I can't seem to import the module:

`pip install pyxero`

Requirement already satisfied: pyxero in ./lib/python3.5/site-packages
Requirement already satisfied: six>=1.8.0 in ./lib/python3.5/site-packages (from pyxero)
Requirement already satisfied: python-dateutil>=2.1 in ./lib/python3.5/site-packages (from pyxero)
Requirement already satisfied: requests>=1.1.0 in ./lib/python3.5/site-packages (from pyxero)
Requirement already satisfied: PyJWT==1.4.0 in ./lib/python3.5/site-packages (from pyxero)
Requirement already satisfied: cryptography>=1.3.1 in ./lib/python3.5/site-packages (from pyxero)
Requirement already satisfied: requests-oauthlib>=0.3.0 in ./lib/python3.5/site-packages (from pyxero)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./lib/python3.5/site-packages (from requests>=1.1.0->pyxero)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.5/site-packages (from requests>=1.1.0->pyxero)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./lib/python3.5/site-packages (from requests>=1.1.0->pyxero)
Requirement already satisfied: idna<2.7,>=2.5 in ./lib/python3.5/site-packages (from requests>=1.1.0->pyxero)
Requirement already satisfied: asn1crypto>=0.21.0 in ./lib/python3.5/site-packages (from cryptography>=1.3.1->pyxero)
Requirement already satisfied: cffi>=1.7 in ./lib/python3.5/site-packages (from cryptography>=1.3.1->pyxero)
Requirement already satisfied: oauthlib>=0.6.2 in ./lib/python3.5/site-packages (from requests-oauthlib>=0.3.0->pyxero)
Requirement already satisfied: pycparser in ./lib/python3.5/site-packages (from cffi>=1.7->cryptography>=1.3.1->pyxero)

`
from xero.auth import PublicCredentials
ImportError: No module named 'xero.auth'; 'xero' is not a package
`

**Comment by chandra-technicise** [comment] 2017-10-23 09:40
I am also facing same issue..

**Comment by ollytheninja** [comment] 2017-12-03 22:58
Do you have a local module called `xero`? I ran into the same problem because by having a `xero.py` file, python was looking for `auth` in that instead of in the pyxero library

**Comment by rhelms** [comment] 2018-08-03 05:05
I did have a lib.xero module, but I renamed this to lib.xero_api and I'm still getting a ImportError: cannot import name 'Xero' error for a 'from xero import Xero' under Python 3.5.

I wonder if the project need `from __future__ import absolute_import` through out so the relative imports don't get confused under Python 3.5.

**Comment by schinckel** [comment] 2021-03-05 01:42
I'm going to close this, as I believe it's not a bug in PyXero.

**Closed by schinckel** 2021-03-05 01:42 UTC
